package mcpiapi

// Block types
const (
	AIR                  = 0
	STONE                = 1
	GRASS                = 2
	DIRT                 = 3
	COBBLESTONE          = 4
	WOOD_PLANKS          = 5
	SAPLING              = 6
	BEDROCK              = 7
	WATER_FLOWING        = 8
	WATER                = WATER_FLOWING
	WATER_STATIONARY     = 9
	LAVA_FLOWING         = 10
	LAVA                 = LAVA_FLOWING
	LAVA_STATIONARY      = 11
	SAND                 = 12
	GRAVEL               = 13
	GOLD_ORE             = 14
	IRON_ORE             = 15
	COAL_ORE             = 16
	WOOD                 = 17
	LEAVES               = 18
	SPONGE               = 19 // added
	GLASS                = 20
	LAPIS_LAZULI_ORE     = 21
	LAPIS_LAZULI_BLOCK   = 22
	SANDSTONE            = 24
	BED                  = 26
	POWERED_RAIL         = 27 // added
	COBWEB               = 30
	GRASS_TALL           = 31
	DEAD_BUSH            = 32 // adeed
	WOOL                 = 35
	FLOWER_YELLOW        = 37
	FLOWER_CYAN          = 38
	MUSHROOM_BROWN       = 39
	MUSHROOM_RED         = 40
	GOLD_BLOCK           = 41
	IRON_BLOCK           = 42
	STONE_SLAB_DOUBLE    = 43
	STONE_SLAB           = 44
	BRICK_BLOCK          = 45
	TNT                  = 46
	BOOKSHELF            = 47
	MOSS_STONE           = 48
	OBSIDIAN             = 49
	TORCH                = 50
	FIRE                 = 51
	STAIRS_WOOD          = 53
	CHEST                = 54
	DIAMOND_ORE          = 56
	DIAMOND_BLOCK        = 57
	CRAFTING_TABLE       = 58
	SEEDS                = 59 // added
	FARMLAND             = 60
	FURNACE_INACTIVE     = 61
	FURNACE_ACTIVE       = 62
	SIGN_POST            = 63 // added
	DOOR_WOOD            = 64
	LADDER               = 65
	RAIL                 = 66 // added
	STAIRS_COBBLESTONE   = 67
	WALL_SIGN            = 68 // added
	DOOR_IRON            = 71
	REDSTONE_ORE         = 73
	GLOWING_REDSTONE_ORE = 74 // added
	SNOW                 = 78
	ICE                  = 79
	SNOW_BLOCK           = 80
	CACTUS               = 81
	CLAY                 = 82
	SUGAR_CANE           = 83
	FENCE                = 85
	PUMPKIN              = 86 // adeed
	NETHERRACK           = 87 // added
	GLOWSTONE_BLOCK      = 89
	JACK_O_LANTERN       = 91 // added
	CAKE_BLOCK           = 92 // added
	BEDROCK_INVISIBLE    = 95
	TRAP_DOOR            = 96 // added
	STONE_BRICK          = 98
	IRON_BARS            = 101
	GLASS_PANE           = 102
	MELON                = 103
	PUMPKIN_STEM         = 104 // added
	MELON_STEM           = 105 // added
	FENCE_GATE           = 107
	BRICK_STAIRS         = 108 // added
	STONE_BRICK_STAIRS   = 109 // added
	NETHER_BRICK         = 112 // added
	NETHER_BRICK_STAIRS  = 114 // added
	SANDSTONE_STAIRS     = 128 // added
	EMERALD_ORE          = 129 // added
	SPRUCE_WOOD_STAIRS   = 134 // added
	BIRCH_WOOD_STAIRS    = 135 // added
	JUNGLE_WOOD_STAIRS   = 136 // added
	COBBLESTONE_WALL     = 139 // added
	CARROTS              = 141 // added
	POTATO               = 142 // added
	QUARTZ_BLOCK         = 155 // added
	QUARTZ_STAIRS        = 156 // added
	WOODEN_DOUBLE_SLAB   = 157 // added
	WOODEN_SLAB          = 158 // added
	HAY_BLOCK            = 170 // added
	CARPET               = 171 // added
	BLOCK_OF_COAL        = 173 // added
	BEETROOT             = 244 // added
	STONE_CUTTER         = 245 // added
	GLOWING_OBSIDIAN     = 246
	NETHER_REACTOR_CORE  = 247
	UPDATE_GAME_BLOCK_1  = 248 // added
	UPDATE_GAME_BLOCK_2  = 249 // added
	LAST                 = 255 // added
)
